CREATE TABLE IF NOT EXISTS `precificacao_configuracoes` (
  `id` int AUTO_INCREMENT NOT NULL,
  `escritorioId` int,
  `aluguel` decimal(15,2) DEFAULT '0',
  `energia` decimal(15,2) DEFAULT '0',
  `agua` decimal(15,2) DEFAULT '0',
  `internet` decimal(15,2) DEFAULT '0',
  `sistemas` decimal(15,2) DEFAULT '0',
  `contador` decimal(15,2) DEFAULT '0',
  `marketing` decimal(15,2) DEFAULT '0',
  `materialEscritorio` decimal(15,2) DEFAULT '0',
  `manutencao` decimal(15,2) DEFAULT '0',
  `impostosFixos` decimal(15,2) DEFAULT '0',
  `folhaFuncionarios` decimal(15,2) DEFAULT '0',
  `proLaboreSocios` decimal(15,2) DEFAULT '0',
  `outros` decimal(15,2) DEFAULT '0',
  `horasProdutivasMes` decimal(8,2) DEFAULT '176',
  `margemLucroDesejada` decimal(5,2) DEFAULT '35',
  `impostosVariaveisPercentual` decimal(5,2) DEFAULT '8',
  `reservaRiscoPercentual` decimal(5,2) DEFAULT '6',
  `custoKm` decimal(8,2) DEFAULT '1.65',
  `seccionalOab` varchar(20) DEFAULT 'OAB-MA',
  `anoTabela` int DEFAULT 2026,
  `ativo` boolean DEFAULT true,
  `createdAt` timestamp NOT NULL DEFAULT (now()),
  `updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `precificacao_configuracoes_id` PRIMARY KEY(`id`)
);

CREATE TABLE IF NOT EXISTS `precificacao_servicos` (
  `id` int AUTO_INCREMENT NOT NULL,
  `codigo` varchar(120) NOT NULL,
  `areaDireito` varchar(80) NOT NULL,
  `nome` varchar(255) NOT NULL,
  `pisoOab` decimal(15,2) DEFAULT '0',
  `percentualExito` decimal(6,4) DEFAULT '0',
  `fonteReferencia` text,
  `ativo` boolean DEFAULT true,
  `createdAt` timestamp NOT NULL DEFAULT (now()),
  `updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `precificacao_servicos_id` PRIMARY KEY(`id`),
  CONSTRAINT `precificacao_servicos_codigo_unique` UNIQUE(`codigo`)
);

CREATE TABLE IF NOT EXISTS `propostas_honorarios` (
  `id` int AUTO_INCREMENT NOT NULL,
  `processoId` int,
  `clienteId` int,
  `responsavelId` int,
  `areaDireito` varchar(80) NOT NULL,
  `servicoCodigo` varchar(120) NOT NULL,
  `valorCausa` decimal(15,2) DEFAULT '0',
  `complexidade` int DEFAULT 3,
  `urgencia` int DEFAULT 3,
  `risco` int DEFAULT 3,
  `horasTecnicas` decimal(8,2) DEFAULT '0',
  `horasAdministrativas` decimal(8,2) DEFAULT '0',
  `horasDeslocamento` decimal(8,2) DEFAULT '0',
  `kmTotal` decimal(10,2) DEFAULT '0',
  `despesasDiretas` decimal(15,2) DEFAULT '0',
  `custoOperacional` decimal(15,2) DEFAULT '0',
  `pisoOabAplicado` decimal(15,2) DEFAULT '0',
  `valorMinimoTecnico` decimal(15,2) DEFAULT '0',
  `valorRecomendado` decimal(15,2) DEFAULT '0',
  `valorPremium` decimal(15,2) DEFAULT '0',
  `entradaSugerida` decimal(15,2) DEFAULT '0',
  `honorarioExito` decimal(15,2) DEFAULT '0',
  `margemRealEstimada` decimal(8,2) DEFAULT '0',
  `payloadCalculo` text,
  `status` enum('rascunho','enviada','aprovada','recusada','cancelada') DEFAULT 'rascunho',
  `createdAt` timestamp NOT NULL DEFAULT (now()),
  `updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT `propostas_honorarios_id` PRIMARY KEY(`id`)
);
